### ISSUE TITLE
measurements lib inside .base breaks ANEs

### ISSUE THREAD

**Issue by ventr1x** [distriqt/ANE-GooglePlayServices#10]
Upgrading gps to the newest version (19th March) breaks every other ANE using google measurements, especially your own Firebase ANEs.

I'm currently using a version from last September and everything works (I need to upgrade for ad networks).

Replacing only the .base ANE with a newer version breaks e.g. Firebase. 
So I guess you included measurements into the base ANE for whatever reason.
Could you look into this and maybe remove measurements from .base again?

**Comment by marchbold** [comment]
Hi,

We are still in progress of updating our ANEs, please be patient as we complete this major update.

**Comment by marchbold** [comment]
You can follow the progress here: https://github.com/orgs/distriqt/projects/2

We aim to have it complete by Wednesday

**Comment by ventr1x** [comment]
What exactly should I look for there? I see an entry for Firebase, but I don't really care about Firebase nor AndroidX in this issue but about including measurements into the .base ANE - which was never the case in the past.
Will this be removed again, best even added to its own ANE as the Firebase ANE conflicts with e.g. IronSrc right now?

**Comment by marchbold** [comment]
Can you clarify exactly what extensions are conflicting?

**Comment by marchbold** [comment]
FYI, the measurements lib has always been in the base ane

**Comment by ventr1x** [comment]
How does it suddenly result in a conflict after updating it to the newest version?
Using newest Firebase and base ANE points to duplicate measurements lib being included.
The same goes for any other ANE using measurements, e.g. any admob plugin (e.g. IronSrc).

To test it I removed everything from our App (no external ANE included) and only updated the .base ANE from last September to the newest. Throws duplicate lib error while Firebase (no matter the version) is included.

**Comment by marchbold** [comment]
As I said, we are in the midst of a major update. The Android X update includes a major GPS update, so as of right now GPS and Firebase are out-of-sync, until we release the Firebase update.

This has been part of the AndroidX release as the version of GPS was being held back because we couldn't release it without the AndroidX update.

So if the conflict is between Firebase and GPS then please wait until we have released both updates.
