### ISSUE TITLE
Third party ANE problem with v20.2.1

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-GooglePlayServices#14]
Hi!

After last update (v20.2.1) I notice that this ANE (https://dev.tapjoy.com/sdk-integration/air/) dont work. Initialized failed.
It's work fine with v20.2.0. May be you now what happened?
Thx!

**Comment by marchbold** [comment]
Which ANEs are you using? We have split out the ads identifier from the base ANE to avoid packaging Ads with every application. You could try adding the `com.distriqt.playservices.AdsIdentifier.ane` ANE?

**Comment by Mintonist** [comment]
Thx! It helps!

**Comment by marchbold** [comment]
We are updating the documentation for the ANEs, but really only if you are using advertising of any description (AdMob through the Adverts ANE for example). If you are then add this new extension.
