### ISSUE TITLE
Getting a Series of Errors Related to Play Services When Compiling For iOS

### ISSUE THREAD

**Issue by ArifRocks** [distriqt/ANE-GooglePlayServices#15]
Hi there. Am currently trying to compile for iOS and using the following libraries - Adverts, Applications, Facebook API, Game Services and InApp Billing. The Android version works fine but this error appears when compiling for iOS. 

Am using the latest version of all the libraries which were downloaded yesterday. Any help would be appreciated. Thank you! 

![image](https://user-images.githubusercontent.com/19954118/94591316-d30ed980-027f-11eb-8525-18a1fef114aa.png)

**Comment by marchbold** [comment]
The play services references in there are just warnings, stating that it is using the default implementation and is completely expected on iOS, and any non-android platforms. 

The error you are seeing is the "Undefined symbolds ... __isPlatformVersionAtLeast". This means you either haven't added or have an old version of the lib clang in your AIR SDK.

Copy the library `libclang_rt.ios.a` into your AIR SDK and place it at: `[AIR_SDK]/lib/aot/lib`

You can grab the library file [here](https://www.dropbox.com/s/esstq8dmerur8v8/libclang_rt.ios.a?dl=0)

https://www.dropbox.com/s/esstq8dmerur8v8/libclang_rt.ios.a?dl=0

Please vote for this issue: https://github.com/Gamua/Adobe-Runtime-Support/issues/113

**Comment by ArifRocks** [comment]
Yes, that's resolved the issue. Thank you for your help :)

**Comment by marchbold** [comment]
Great to hear!
