### ISSUE TITLE
Is com.google.android.play.ane required now?

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-GooglePlayServices#16]
Hi!

I don't find tips about new com.google.android.play.ane
Is com.google.android.play.ane required now?
Thx!

P.S. Is 3rd version of GPS bring some sdkTarget or Android device version restrictions?

**Comment by marchbold** [comment]
If it is required by an ANE it will be listed in the "add the extension" documentation. 

Currently this is only 2 extensions, 
- ApplicationRater for the new ["In-App Review Activity"](https://docs.airnativeextensions.com/docs/applicationrater/review-controller/); and
- InAppBilling for ["In App Updates"](https://docs.airnativeextensions.com/docs/inappbilling/in-app-updates)
