### ISSUE TITLE
Check if device supports GooglePlayServices

### ISSUE THREAD

**Issue by leossmith** [distriqt/ANE-GooglePlayServices#17]
Is there a way to check if the device running supports GooglePlayServices? something like GooglePlayServices.isSupported would be helpful in some cases in Android.

**Comment by marchbold** [comment]
Have a look at the availability API:

https://github.com/distriqt/ANE-GooglePlayServices/wiki/API-Availability

**Comment by leossmith** [comment]
Thank you that did the trick.
