### ISSUE TITLE
Conflict with com.milkmangames.extensions.GoogleServices.ane

### ISSUE THREAD

**Issue by SamYStudiO** [distriqt/ANE-GooglePlayServices#2]
Hey,

I'm definitely a distriqt user but since i needed a google analytics ane i had to include milikmangame ones but it looks like their google service ane conflict with distriqt one and so compilation failed, any chance there is a tip to get both work or even better a distriqt google analytics extension? :)

Thx

**Comment by marchbold** [comment]
If an ANE includes the GoogleServices library, you can try to simply not include this ANE. As long as there is a recent version of the library included it should work. 

If however the ANE includes an old version of the library without the necessary components for other services there isn't a lot we can do. Contact the ANE developer and get them to separate the Google Play Services library as we have.
