### ISSUE TITLE
META-INF/ANE/iPhone-ARM/libfirebasecore.a are required to have universal iOS libraries

### ISSUE THREAD

**Issue by ChacHauLam** [distriqt/ANE-GooglePlayServices#25]
Hi,

My setup is:
- Windows
- Visual Studio code
- ActionScript and MXML extension for Visual Studio Code
- AIRSDK 50.0.1.3
- jdk-11.0.2
- APM

When building to .ipa I get this error:

_Warning: Using default implementation for native extension 'androidx.constraintlayout'
Warning: Using default implementation for native extension 'com.bumptech.glide'
Warning: Using default implementation for native extension 'com.google.guava'
Warning: Using default implementation for native extension 'androidx.cardview'
Warning: Using default implementation for native extension 'com.google.code.gson'
Warning: Using default implementation for native extension 'androidx.appcompat'
Warning: Using default implementation for native extension 'com.distriqt.playservices.AppSet'
Warning: Using default implementation for native extension 'com.jetbrains.kotlin'
Warning: Using default implementation for native extension 'com.google.dagger'
Warning: Using default implementation for native extension 'io.reactivex'
Warning: Using default implementation for native extension 'androidx.emoji2'
Warning: Using default implementation for native extension 'com.google.protobuflite'
Warning: Using default implementation for native extension 'com.distriqt.playservices.CloudMessaging'
Warning: Using default implementation for native extension 'com.google.android.datatransport'
Warning: Using default implementation for native extension 'androidx.exifinterface'
Warning: Using default implementation for native extension 'androidx.core'
Warning: Using default implementation for native extension 'androidx.browser'
Warning: Using default implementation for native extension 'androidx.work'
Warning: Using default implementation for native extension 'io.grpc'
Warning: Using default implementation for native extension 'androidx.vectordrawable'
Warning: Using default implementation for native extension 'com.distriqt.playservices.Base'
Warning: Using default implementation for native extension 'androidx.room'
..java.base/java.lang.Thread.getStackTrace(Thread.java:1606)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.InvalidInputException.<init>(InvalidInputException.java)
..com.adobe.air.ipa.IPAPackager.processExtensions(IPAPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)
Stack trace:
Invalid input: Error: META-INF/ANE/iPhone-ARM/libfirebasecore.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same._

Note. I'm assuming this error is caused by ANE-GooglePlayServices as it contains com.google.firebase.core.ane? Apologies if it isn't and should be in under a different area.

Thanks

**Comment by marchbold** [comment]
Please set the minimum ios version to 11. We are making this change across all our extensions in line with the latest Xcode release.

**Comment by ChacHauLam** [comment]
Thanks, that worked!
