### ISSUE TITLE
Error When ANE Is included in project

### ISSUE THREAD

**Issue by izzmeifter** [distriqt/ANE-GooglePlayServices#3]
We require this ANE to be used with the FacebookSDK ANE but when including this ANE and trying to compile, we get the following Error. This has been tested with AIR 18 and 19

![screen shot 2015-10-26 at 7 08 32 pm](https://cloud.githubusercontent.com/assets/4297079/10749901/4537e726-7c35-11e5-8d0c-1ae3668ba464.png)

Thoughts?

**Comment by marchbold** [comment]
Have you tried increasing the memory available to java?

**Comment by izzmeifter** [comment]
Yes. We are using IntelliJ 14, and have allocated over 2 gig of ram following these instructions

https://www.jetbrains.com/idea/help/increasing-memory-heap.html

 It doesn't seem to help. Removing this ANE, everything compiles quite quick (with 8 other ANES from District) but adding this one, results with this everytime. I'll continue investigating but as of now, we have no solution.

**Comment by izzmeifter** [comment]
Sorry guys. we were increasing the memory in the wrong place. For Flex/AIR projects it needs to be done via the settings and not the vmoptions file. All is working now! - Thanks guys!

**Comment by marchbold** [comment]
No problems, glad you found the issue.
