### ISSUE TITLE
Duplicate symbols in com.google.firebase.core

### ISSUE THREAD

**Issue by marchbold** [distriqt/ANE-GooglePlayServices#30]
I started to test a build that was compiling flawlessly with 50.2.3.5 before upgrading to last ANEs that was creating problems.

As [Michoko92](https://github.com/Michoko92), I had the same issue with the vanilla 50.2.3.6:
![image](https://github.com/distriqt/ANE-GooglePlayServices/assets/21979056/2f3f554a-19f1-4d74-996a-a134be9bc5ef)

After replacing ld64, I get the following error:
![image](https://github.com/distriqt/ANE-GooglePlayServices/assets/21979056/ced1ed9d-a7cd-412e-9959-c191e8782719)

I don't know if I migrate to the last ANEs it would solve the problem. Maybe @marchbold knows more about it.

_Originally posted by @marcanw in https://github.com/distriqt/ANE-GooglePlayServices/issues/28#issuecomment-1745651246_

**Comment by Mintonist** [comment]
I download the lastest version com.google.firebase.core.ane but get the same error.

**Comment by marchbold** [comment]
Is it exactly the same? Can you clear all the caches in your ide to ensure you aren't using a cached version. The symbol has been removed from the latest release  so the error definitely should be different if it is still occurring.

**Comment by Mintonist** [comment]
Yes, there is different error:
ld64: error: duplicate symbol: _distriqt_core_ctx >>> defined in Core.m:40 (Core\Core.m:40) >>> AppData\Local\Temp\3ca63786-dfcb-4ca0-ac22-0935ae14f9cd\libcom.distriqt.Core.a(Core.o) >>> defined in AppData\Local\Temp\3be7aa5c-7eae-4371-83fb-b43229bc4ae5\libcom.google.firebase.core.a(FirebaseCore.o) ld64: error: duplicate symbol: _distriqt_core_v >>> defined in Core.m:41 (Core\Core.m:41) >>> AppData\Local\Temp\3ca63786-dfcb-4ca0-ac22-0935ae14f9cd\libcom.distriqt.Core.a(Core.o) >>> defined in AppData\Local\Temp\3be7aa5c-7eae-4371-83fb-b43229bc4ae5\libcom.google.firebase.core.a(FirebaseCore.o) Compilation failed while executing : ld64

**Comment by marchbold** [comment]
Please double check that you have updated and cleared any cached versions. This symbol has been removed from the firebase ANE.

**Comment by Mintonist** [comment]
```
<id>com.google.firebase.core</id>
<versionNumber>32.1.106</versionNumber>
```

Yes, I use Inelij Idea, I manualy clear temp filders and restart IDE

**Comment by marchbold** [comment]
Can you try deleting the temp directory it's using? `AppData\Local\Temp\3be7aa5c-7eae-4371-83fb-b43229bc4ae5` 

Those symbols definitely aren't in the lib.

**Comment by Mintonist** [comment]
Of course!
You can see others temp pathes:
```
ld64: error: duplicate symbol: _distriqt_core_ctx >>> defined in Core.m:40 (Core\Core.m:40) >>> \AppData\Local\Temp\9814d0ff-d43f-49f0-b929-95f25f387351\libcom.distriqt.Core.a(Core.o) >>> defined in \AppData\Local\Temp\479e9327-8ed6-4dd1-81c4-aa1e438db413\libcom.google.firebase.core.a(FirebaseCore.o) 

ld64: error: duplicate symbol: _distriqt_core_v >>> defined in Core.m:41 (Core\Core.m:41) >>> \AppData\Local\Temp\9814d0ff-d43f-49f0-b929-95f25f387351\libcom.distriqt.Core.a(Core.o) >>> defined in \AppData\Local\Temp\479e9327-8ed6-4dd1-81c4-aa1e438db413\libcom.google.firebase.core.a(FirebaseCore.o) 

Compilation failed while executing : ld64
```

**Comment by marchbold** [comment]
Not sure what else to suggest, the symbol definitely has been removed from the current release. You don't have an old version somewhere in your build?

**Comment by Mintonist** [comment]
Is any chance that your local version is different from repo version?

Can you try build simple|test project on your side with ANE file from repo (https://github.com/distriqt/ANE-GooglePlayServices/blob/master/lib/com.google.firebase.core.ane)?

**Comment by marchbold** [comment]
If you are still having issues then it may be related to the AIR SDK, there appears to be an issue in the 50.2.3.6 with a new linker. 

Try using this update that Harman is working on

https://transfer.harman.com/link/Brh2YO2NAELPL99TZbgimo

**Comment by Mintonist** [comment]
Thanks a lot!
Yes, it has been solved with new linker
