### ISSUE TITLE
Cannot compile the app after updating to v29.0.2

### ISSUE THREAD

**Issue by bbsdevelopement** [distriqt/ANE-GooglePlayServices#32]
I have updated a number of ANEs

- com.distriqt.firebase | 9.0.2 
- com.distriqt.firebase.Crashlytics | 9.0.2 
- com.distriqt.firebase.RemoteConfig | 9.0.2 
- com.distriqt.Notifications | 6.7.0 
- com.distriqt.PDFReader | 5.2.0 
- com.distriqt.Permissions | 4.0.2 
- com.distriqt.Scanner | 5.1.0 
- com.distriqt.Core | 7.5.1 
- com.distriqt.square.okhttp3 | 3.140.900 
- com.distriqt.playservices.Analytics | 18.0.303 
- com.distriqt.playservices.Base | 18.4.1 
- com.distriqt.playservices.CloudMessaging | 17.2.0
- androidx.core | 1.13.100
- androidx.multidex | 2.0.105 
- androidx.appcompat | 1.6.104 
- com.google.dagger | 2.28.304
- com.google.protobuflite | 3.21.120 
- com.google.android.datatransport | 3.0.7 
- com.google.firebase.core | 33.0.0
- com.jetbrains.kotlin | 1.8.220 

Now the following error occurs:
With SDK 50.2.5.1, the creation of the app is aborted with an error message.
With SDK 51.0.2.1 the APK is created and can also be installed. The app crashes immediately on startup.

Result after several attempts:  
If I change com.distriqt.playservices.Base from version 18.4.0 back to 18.2.4, the app works.
The error occurs with all versions from v29.0.0 of ANE-GooglePlayServices.

Extract from the log file
Version in APK = 50.2.5.1, version of ADT = 50.2.5.1
Gradle build where ADT is using JRE version 17.0.10
but where Gradle will be using the JDK from C:/Program Files/Android/Android Studio1/jbr\bin\java.exe
Gradle build command:  C:/Program Files/Android/Android Studio1/jbr\bin\java.exe -Xmx2048m -Dorg.gradle.appname=gradlew -Dorg.gradle.jvmargs=-Xmx2048m -Duser.dir="D:\flash_work\prosmap_BT40_1\bin\AndroidStudioProject" -DAIR_GRADLE_KEYPWD=xxxxxx -DAIR_GRADLE_STOREPWD=xxxxxx -cp "D:\flash_work\prosmap_BT40_1\bin\AndroidStudioProject\gradle\wrapper\gradle-wrapper.jar";"D:\Progs\AirSDK\AIRSDK_50_2_5_1\lib\android\bin\gradle-cli.jar" org.gradle.wrapper.GradleWrapperMain :app:assembleDebug
..java.base/java.lang.Thread.getStackTrace(Thread.java:1621)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.ADTException.<init>(ADTException.java)
..com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
..com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)
Stack trace:
Unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:desugarDebugFileDependencies'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexFileDependenciesTask$DexFileDependenciesWorkerAction
   > Error while dexing.

**Comment by marchbold** [comment]
Please see the discussion here:

https://github.com/airsdk/Adobe-Runtime-Support/issues/3236

Short answer, either:

- set your minimum version to 24
- use the Android Studio Project output to build
- wait for an update from Harman

Or I believe people have had success with downgrading the android build tools to v33
