### ISSUE TITLE
App Invites

### ISSUE THREAD

**Issue by shamruk** [distriqt/ANE-GooglePlayServices#4]
I am going to add google App Invites to my game ( https://developers.google.com/app-invites/ , https://developers.google.com/app-invites/android/guides/app ).

Can this ANE help me with this?

**Comment by marchbold** [comment]
Hi,

This ANE is only a library wrapper. It contains the Google Play Services library used by many of our extensions. 

You can see all our extensions at: http://airnativeextensions.com

Cheers

**Comment by shamruk** [comment]
So do you wrap Google services App Invites in this wrapper or you don't wrap them?

**Comment by marchbold** [comment]
Hi,
There is no functionality exposed with this ANE, it just contains the Google Play Services library.
We are yet to develop an ANE to use the App Invites Beta. Feel free to drop a suggestion on our development site: http://distriqt.uservoice.com
Cheers

**Comment by shamruk** [comment]
thanks, looking forward
