### ISSUE TITLE
Compile errors when including this extension

### ISSUE THREAD

**Issue by philvessey** [distriqt/ANE-GooglePlayServices#5]
Im building for Android and my project has the following extensions:

Adverts
AndroidSupport
Core
Dialog
Notifications

Whenever I include the GooglePlayServices ane and compile I get the following:

..\..\..\..\Users\phill\AppData\Local\Temp\5128dd27-d5e6-4128-9da3-156fabcd22cc\out\com\google\android\gms\maps\model\internal\zzc.smali[0,0] null

and the compile fails. It works fine everytime without this extension being included but a lot of the ANEs need this

**Comment by distriqt-developer** [comment]
Hi,

This will be an issue with one of the other ANEs you are using. Do you mind posting in the relevant repository?

Cheers
