### ISSUE TITLE
Package ios ipa warning

### ISSUE THREAD

**Issue by ReginaSun** [distriqt/ANE-GooglePlayServices#7]
Is there a warning that the package is correct?

I have <extensionID>com.distriqt.playservices.Ads</extensionID> in xml or I don't need to write it.

![image](https://user-images.githubusercontent.com/20833433/63013004-da2d2980-bebd-11e9-8c1a-1a1401adba23.png)

**Comment by marchbold** [comment]
The playservices ANEs are only  needed for Android builds and will just use the default implementation on other platforms.

You can either remove them for other platforms or just ignore the warning. It won't affect the build.

**Comment by ReginaSun** [comment]
OK. 
Thank you.
