### ISSUE TITLE
Native extensions for FREE to Play game

### ISSUE THREAD

**Issue by DQvsRA** [distriqt/ANE-GooglePlayServices#8]
Hello DISTRIQT team,

My name Vladimir Minkin and I'm developing free to play game - PUZZLIC using AIR engine:
https://play.google.com/store/apps/details?id=tech.logico.game.puzzlic
I'm the only one developer, already put a lot of afford and time to make the game real, bought graphics and spent a lot of time working with illustrator. For now I can't afford to publish on iOS market and buy a license for Apple app development. Same thing with ANE, for now I can't afford it, currently I'm using Milkman ANEs which I have not bought by myself but got it from my brother previous projects where he used on the company behalf. I know how to write ANE, did it in the past but for now don't have time to reimplement everything by myself. The app use InApp-Purchase ANE and Vibration. Currently this project is more like a proof of my potential as company's employee, kind of showcase of what I'm capable to do.
So, I want to ask are there any other ways I can use your ANEs in my app, some kind special agreement for future profit share if any or anything else?

Best regards,
Vladimir Minkin

**Comment by marchbold** [comment]
If you have a proposal we are willing to listen however I can't guarantee we are in a position to give anything away.  Send an email to our team at airnativeextensions@distriqt.com
